Q1

In [3]:
import pandas as pd

train_df = pd.read_csv("ann-train.data", sep=r'\s+', header=None)
test_df = pd.read_csv("ann-test.data", sep=r'\s+', header=None)

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

X_train = train_df.iloc[:, :-1].values
y_train = train_df.iloc[:, -1].values

X_test = test_df.iloc[:, :-1].values
y_test = test_df.iloc[:, -1].values

k = 3

knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[  39    7   27]
 [   1   18  158]
 [  13   15 3150]]


Q2

In [6]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

# Convert to binary classification (normal = 0 vs abnormal = 1)
y_train = (y_train == 1).astype(int)
y_test = (y_test == 1).astype(int)

# Standardise features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Default threshold of 0.5
y_pred_prob = model.predict_proba(X_test)[:, 1]
y_pred = (y_pred_prob >= 0.5).astype(int)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (threshold=0.5):")
print(cm)

# Varying the threshold
thresholds = [0.3, 0.5, 0.7]
for thresh in thresholds:
    y_pred_thresh = (y_pred_prob >= thresh).astype(int)
    cm_thresh = confusion_matrix(y_test, y_pred_thresh)
    print(f"Confusion Matrix (threshold={thresh}):")
    print(cm_thresh)

Confusion Matrix (threshold=0.5):
[[3335   20]
 [  14   59]]
Confusion Matrix (threshold=0.3):
[[3327   28]
 [  11   62]]
Confusion Matrix (threshold=0.5):
[[3335   20]
 [  14   59]]
Confusion Matrix (threshold=0.7):
[[3343   12]
 [  22   51]]


Q3

a)

In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso

df = pd.read_csv("pokemonregr.csv")
df = df.dropna()

# X = all columns except the last column
X = df.iloc[:, :-1].values

# y = last column
y = df.iloc[:, -1].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train linear regression model
lr = LinearRegression()
lr.fit(X_scaled, y)
print("Linear coefficients:", lr.coef_)

# Train Lasso regression model (L1 regularisation)
lasso = Lasso(alpha=10)
lasso.fit(X_scaled, y)
print("Lasso coefficients:", lasso.coef_)

Linear coefficients: [ 12.15337036  17.47803453  57.77623107   0.79121435   4.29529442
 -12.17646811]
Lasso coefficients: [ 2.13231163 16.69367581 51.52809771  0.          0.         -0.        ]


b)

In [20]:
from sklearn.linear_model import Ridge

# Train ridge regression model (L2 regularisation)
ridge = Ridge(alpha=10)
ridge.fit(X_scaled, y)
print("Ridge coefficients:", ridge.coef_)

Ridge coefficients: [ 12.23043558  17.43296018  56.903939     0.90861136   4.42033464
 -11.95443408]


After standardisation, Ridge shrinks all coefficients slightly while Lasso drives some coefficients to zero, demonstrating feature selection.